### ISSUE TITLE
Aisu disabling buffer modification property

### ISSUE THREAD

**Issue by jlombs** [kirbyfan64/aisu#2]
Based on my [issue](https://github.com/howl-editor/howl/issues/355) at howl, I've tracked it down to aisu. Upon following aisu's installation instructions:

`$ mkdir ~/.howl/bundles` 
`$ cd ~/.howl/bundles`
`$ git clone https://github.com/kirbyfan64/aisu.git`

the buffer `modified` property becomes perpetually set to `false`. As a result, anything that depends on checking whether an active buffer has been modified will fail, such as `save-and-quit`, or prompts relying on confirming actions based on a modified buffer, etc. 

This is reproducible both on my laptop running Bunsen Labs under Debian 4.9.18, and on my desktop running Ubuntu 16.04, by using fresh clones of howl installed through their recommended commands, and running the above installation commands for aisu. Removing the aisu bundle resolves the issue.

**Comment by refi64** [comment]
Turns out this actually *is* a bug in Howl that just happened to manifest itself via something Aisu was doing. I just committed a workaround; if you reinstall Aisu, this should be fixed now.
